[project]
name = "alite"
version = "0.3.0.a0"
description = "Asynchronous SQLite3 library"
readme = "README.md"
authors = [
    { name = "ZyubyL", email = "zyubyl@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/zyubyl/alite"
Issues = "https://github.com/zyubyl/alite/issues"

[build-system]
requires = ["setuptools>=84.0.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "setuptools>=84.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
